version: "3.7"
services:
  luminati:
    image: luminati/luminati-proxy:latest
    container_name: luminati
    restart: always
    ports: ["22999:22999", "22225:22225", "24000:24000", "24002:24002"]
    environment:
      LPM_PROXY_PORT: 22225
      LPM_WWW_WHITELIST_IPS: "0.0.0.0/0"
      LPM_CONFIG: "/etc/luminati/conf/.luminati.json"
    command: ["luminati"]
    volumes:
      - ./conf:/etc/luminati/conf
    networks:
      static-network:
        ipv4_address: 172.20.128.2
  standalone-chrome:
    image: selenium/standalone-chrome:3
    container_name: standalone-chrome
    ports: ["4444:4444"]
    networks:
      static-network:
        ipv4_address: 172.20.128.1
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16